// Runtime environment configuration
// In production, this file is generated by the Vercel build step
// or replaced with actual values. Locally, edit this directly.
window.__ENV__ = {
  API_BASE_URL: '', // empty = same origin; set to Railway URL in production
};
