
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Build environments (e.g. Railway image build) may not provide DATABASE_URL.
// Use a local-safe fallback for `prisma generate`; runtime/migrations still use
// the real DATABASE_URL from environment.
const datasourceUrl =
  process.env.DATABASE_URL?.trim() || "postgresql://bchubkey:bchubkey@localhost:5432/bchubkey";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: datasourceUrl,
  },
});
